import Head from 'next/head';
import { Main } from '@/components/Main';
import { useEffect } from 'react';

export default function Home() {
  useEffect(() => {
    //run when mounting
    document.body.style.backgroundColor = 'gray';

    //run when unmounting
    return () => {
      document.body.style.backgroundColor = '';
    };
  }, []);

  return (
    <>
      <Head>
        <title>shun kusakabe | portfolio site</title>
        <meta
          name="description"
          content="This is Shun's portfolio site. Generated by create next app"
        />
      </Head>

      <Main title="index" />
    </>
  );
}
